BIPA-8-3/BIZSurvey_FRONT

src/components/common/Container.jsx, src/style/Container.module.css
[Feat] : search 영역 추가
어떤 변경 사항이 있나요?
=> [Feat] : search 영역 추가

src/App.js, src/components/common/Container.jsx, src/components/common/Search.jsx, src/style/Common.css, src/style/Search.module.css
[Refactor] : search 컴포넌트 분리
어떤 변경 사항이 있나요?
=> [Refactor] : search 컴포넌트 분리

package.json, src/components/community/CommunityWrite.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx
[Feat] : 에디터 수정
어떤 변경 사항이 있나요?
=> [Feat] : 에디터 수정

src/components/common/Chart.jsx, src/components/survey/surveyResult/PostResult.jsx, src/components/survey/surveyResult/SurveyResult.jsx, src/routes/Router.js
최대 글자 20
chart 겹치지 않게 글자수 제한
어떤 변경 사항이 있나요?
=> [Refactor] : chart 수정

src/components/user/Mypage.jsx, src/components/user/MypageHeader.jsx, src/pages/Layout.jsx, src/style/Common.css, src/style/user/MypageHeader.module.css
[Feat] : mypage 레이아웃
어떤 변경 사항이 있나요?
=> [Feat] : mypage 레이아웃

package.json, src/components/user/Join.jsx, src/components/user/Login.jsx, src/components/user/Mypage.jsx, src/components/user/MypageUserInfo.jsx, src/pages/Layout.jsx, src/style/user/Login.module.css, src/style/user/MypageHeader.module.css, src/style/user/MypageUserInfo.module.css
[Feat] : proxy 추가
어떤 변경 사항이 있나요?
=> [Feat] : proxy 추가

src/components/community/CommunityTable.jsx, src/components/surveyCommunity/SurveyListModal.jsx, src/style/community/Table.module.css
* CommunityTable 컴포넌트 체크 메소드 추가 
* 새로운 게시물 : 'new' 키워드 맵핑
* 베스트 게시물 : 'best' 키워드 맵핑
* 투표를 한 게시물 : '투표' 이모지 맵핑
어떤 변경 사항이 있나요?
=> [Refactor] : Add CommunityTable Functions

src/components/survey/fields/ChoiceField.jsx, src/components/survey/surveyForm/QuestionComp.jsx, src/components/survey/surveyForm/RequiredButton.jsx, src/components/survey/surveyForm/options/TextOption.jsx, src/components/survey/surveyForm/score/ScoreOptionSelect.jsx, src/components/survey/surveyInfo/infoTab/QuestionInfo.jsx, src/components/survey/surveyInfo/infoTab/SurveyInfo.jsx, src/components/survey/surveyInfo/resultTab/PersonalResult.jsx, src/components/survey/surveyInfo/resultTab/PostResult.jsx, src/components/survey/surveyInfo/resultTab/ResultView.jsx, src/components/survey/surveyInfo/resultTab/SurvePostSelect.jsx, src/components/survey/surveyInfo/resultTab/UserList.jsx, src/components/survey/surveyInfo/resultTab/totalOptions/FileList.jsx, src/components/surveyCommunity/CommunitySurveyWrite.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/components/surveyCommunity/survey/FileOption.jsx, src/components/surveyCommunity/survey/SingleOption.jsx, src/components/surveyCommunity/survey/SurveyQuestion.jsx, src/components/surveyCommunity/survey/TextOption.jsx, src/pages/survey/CreateScoreSurveyPage.jsx, src/pages/survey/CreateSurveyPage.jsx, src/pages/survey/EditSurveyPage.jsx, src/pages/survey/SurveyInfoPage.jsx, src/style/survey/ChoiceField.module.css, src/style/survey/FileLIst.module.css, src/style/survey/SurveyTitle.module.css, src/style/survey/TextList.module.css, src/style/survey/UserLIst.module.css
설문지 개인 응답 결과 조회 기능 추가
어떤 변경 사항이 있나요?
=> [Feat] : 설문 개인 응답 조회 기능

src/components/survey/surveyForm/QuestionComp.jsx, src/components/survey/surveyForm/score/ScoreOptionSelect.jsx, src/pages/survey/CreateScoreSurveyPage.jsx, src/routes/Router.js
스타일 경로 수정 및 변수명 수정
어떤 변경 사항이 있나요?
=> [Refactor] : 스타일 경로 수정

src/components/common/Search.jsx, src/components/common/SearchResult.jsx, src/components/common/SearchResultTable.jsx, src/components/common/SurveyCard.jsx, src/components/common/SurveyPostContainer.jsx, src/components/community/ChildComment.jsx, src/components/community/CommunityDetail.jsx, src/components/community/CommunityPost.jsx, src/components/community/ParentsComment.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/routes/Router.js
* 커뮤니티 페이지 검색 기능 추가
어떤 변경 사항이 있나요?
=> [Feat] : add search service

src/components/common/SCommunitySearch.jsx, src/components/common/SCommunitySearchResult.jsx, src/routes/Router.js
* 설문 커뮤니티 검색 서비스 추가
어떤 변경 사항이 있나요?
=> [Feat] : add surveyPost search service

src/components/community/CommunityWrite.jsx, src/components/community/RegisterVote.jsx
* react-quill 을 사용한 게시물 제작 서비스 제작
어떤 변경 사항이 있나요?
=> [Feat] : Add Community Write Service

src/components/common/SurveyCard.jsx, src/components/community/ChildCommentForm.jsx, src/components/community/Comment.jsx, src/components/community/CommunityDetail.jsx, src/components/community/CommunityWrite.jsx, src/components/community/ParentsComment.jsx
=> [Feat] : add childComment service 

src/components/common/SurveyCard.jsx, src/components/surveyCommunity/CommunitySurveyWrite.jsx, src/components/user/MypagePlanDetail.jsx, src/style/user/MypagePlanDetail.module.css
=> [Design] : 플랜 구독 페이지

src/components/admin/AdminClaimInfo.jsx, src/pages/admin/AdminClaimInfoPage.jsx, src/routes/Router.js, src/style/admin/AdminClaimInfo.module.css
[Feat] : admin claim info router 추가
어떤 변경 사항이 있나요?
=> [Feat] : admin claim info router 추가

src/pages/survey/CreateScoreSurveyPage.jsx, src/pages/workspace/Main.jsx, src/pages/workspace/SharedSurvey.jsx, src/style/workspace/SharedFooter.module.css, src/style/workspace/SharedSurvey.module.css
점수 설문 워크스페이스 연동
공유 설문 페이지 구현
Fixes : #100, #114
어떤 변경 사항이 있나요?
=> [Feat] : 점수 설문 워크스페이스 연동 & 공유 페이지 구현

src/components/survey/surveyForm/OptionSelect.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx, src/components/surveyCommunity/SurveyListModal.jsx, src/pages/survey/CreateSurveyPage.jsx, src/pages/survey/EditSurveyPage.jsx
설문 생성 게시글에서 설문 선택시 모달 여닫는 부분 이슈 해결
어떤 변경 사항이 있나요?
=> [Fix] : 설문 게시글 생성 수정

src/components/survey/surveyForm/ScoreQuestion.jsx, src/components/survey/surveyInfo/infoTab/SurveyInfo.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx, src/pages/survey/CreateScoreSurveyPage.jsx, src/pages/survey/EditScoreSurveyPage.jsx
1. 설문 상세 업로드 기능 추가
2. 설문 상세 뒤로가기 버튼 추가
어떤 변경 사항이 있나요?
=> [Feat] : 설문 상세 기능 추가

src/components/common/Header.jsx, src/components/user/MypageHeader.jsx, src/style/Header.module.css
[Feat] : 마이페이지 수정
어떤 변경 사항이 있나요?
=> Dev user[Feat] : 마이페이지 수정

src/components/common/Plan.jsx, src/components/surveyCommunity/CommunitySurveyWrite.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/components/user/MypagePlanDetail.jsx, src/pages/survey/CreateScoreSurveyPage.jsx, src/pages/survey/CreateSurveyPage.jsx, src/pages/survey/Login.jsx
=> [Refactor] : 구독 플랜 수정

src/components/survey/surveyInfo/resultTab/PostResult.jsx, src/components/survey/surveyInfo/resultTab/ResultView.jsx, src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx, src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx, src/pages/workspace/Main.jsx, src/pages/workspace/api.js
외부 공유 통계 구현
- 기본형
- 점수형
Resolves : #123, #129
어떤 변경 사항이 있나요?
=> [Feat] : 외부 공유 통계 구현

src/components/survey/surveyInfo/resultTab/ResultView.jsx, src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx, src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx, src/components/survey/surveyInfo/resultTab/SurvePostSelect.jsx, src/components/survey/surveyInfo/resultTab/personalOption/ScoreResultOption.jsx, src/components/surveyCommunity/EditSurveyCommunity.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/routes/Router.js
체크박스 리렌더링 안되는 이슈 해결
어떤 변경 사항이 있나요?
=> [Refactor] : 점수 설문 체크박스 렌더링 수정

src/components/common/ClaimReasonModal.jsx, src/components/community/CommunityDetail.jsx, src/components/community/ParentsComment.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/components/surveyCommunity/SurveyListModal.jsx
* 신고 기능 추가 
* 신고 모달 추가
어떤 변경 사항이 있나요?
=> [Feat : add Claim service]

src/components/common/Search.jsx, src/components/common/SearchResultTable.jsx, src/style/Search.module.css
[Feat] : 자동완성 수정
어떤 변경 사항이 있나요?
=> [Feat] : 자동완성 수정

src/components/common/SurveyPostContainer.jsx, src/components/survey/surveyInfo/infoTab/SurveyInfo.jsx, src/components/survey/surveyInfo/resultTab/ResultView.jsx, src/components/survey/surveyInfo/resultTab/SurvePostSelect.jsx, src/components/workspace/ManagementModal.jsx, src/components/workspace/MoreMenu.jsx, src/components/workspace/Navbar.jsx, src/components/workspace/ProfileContainer.jsx, src/components/workspace/ShareModal.jsx, src/components/workspace/SurveyCard.jsx, src/components/workspace/SurveyCreateModal.jsx, src/components/workspace/WorkspaceModal.jsx, src/pages/Layout.jsx, src/pages/survey/CreateSurveyPage.jsx, src/pages/survey/EditSurveyPage.jsx, src/pages/survey/SurveyInfoPage.jsx, src/pages/workspace/Main.jsx, src/pages/workspace/WorkspaceContext.js, src/routes/Router.js, src/style/survey/CreatePage.module.css, src/style/survey/EditSurveyPage.module.css, src/style/workspace/ProfileContainer.module.css
- 워크스페이스의 설문지 기능 별도 페이지로 분리
- 관리자 이미지 불러오기 구현
어떤 변경 사항이 있나요?
=> [Refactor] : 워크스페이스의 설문지 기능 별도 페이지로 분리 및 관리자 이미지 불러오기 구현

src/components/common/Plan.jsx, src/components/survey/surveyInfo/resultTab/PersonalResult.jsx, src/components/survey/surveyInfo/resultTab/PostResult.jsx, src/components/survey/surveyInfo/resultTab/ResultView.jsx, src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx
=> [Refactor] : 엑셀 링크 수정

package.json, src/components/workspace/WorkspaceHeader.jsx, src/pages/workspace/WorkspaceContext.js, src/pages/workspace/api.js
- 워크스페이스 접근 권한 추가
- 메모리 제한 설정 Resolves :  #140
어떤 변경 사항이 있나요?
=> [Feat] : 워크스페이스 접근 권한 추가 & 메모리 제한 설정

src/components/surveyCommunity/SurveyCommunityDetail.jsx
=> [Refactor] : 설문 커뮤니티 삭제 api수정

src/components/community/CommunityDetail.jsx, src/components/community/EditCommunityPost.jsx, src/routes/Router.js
=> [Feat] : create EditCommunityPost

src/components/community/CommunityWrite.jsx, src/components/community/EditCommunityPost.jsx, src/components/surveyCommunity/EditSurveyCommunity.jsx
수정 커뮤니티 null 이슈 관련 해결
어떤 변경 사항이 있나요?
=> [Refactor] : 설문 커뮤니티 수정 오류 해결

package.json, src/components/workspace/ProfileContainer.jsx, src/pages/workspace/Main.jsx
- 빌드 메모리 설정 & 관리자 사진 변경
어떤 변경 사항이 있나요?
=> [Refactor] : 빌드 메모리 설정 & 관리자 사진 변경

src/components/admin/AdminDashboard.jsx, src/components/admin/AdminHeader.jsx, src/components/admin/AdminSurveyList.jsx, src/components/common/Header.jsx, src/components/user/Login.jsx, src/components/user/MypageHeader.jsx, src/components/user/MypagePlanDetail.jsx, src/components/user/MypageSurveyList.jsx, src/style/user/MypageSurveyList.module.css
[Feat] : 플랜 변경시 jwt 토큰 재발급
어떤 변경 사항이 있나요?
=> [Feat] : 플랜 변경시 jwt 토큰 재발급

src/components/survey/surveyInfo/resultTab/PersonalResult.jsx, src/components/survey/surveyInfo/resultTab/PostResult.jsx, src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx, src/components/survey/surveyInfo/resultTab/SurvePostSelect.jsx, src/components/survey/surveyInfo/resultTab/UserList.jsx
유저 선택시 userList초기화 이슈 해결
어떤 변경 사항이 있나요?
=> [Refactor] : 설문 개별 통계 userList 수정

src/components/common/SCommunitySearchResult.jsx, src/components/common/SearchResultTable.jsx, src/components/common/SurveyCard.jsx, src/components/common/SurveyPostContainer.jsx, src/components/community/CommunityDetail.jsx, src/components/community/CommunityPost.jsx, src/components/community/CommunityTable.jsx, src/components/community/EditCommunityPost.jsx
=> [Refactor] : refactor community page

src/components/workspace/Navbar.jsx, src/pages/workspace/WorkspaceContext.js
권한 수정 및 Navbar Profile 수정
Resolves : #140
어떤 변경 사항이 있나요?
=> [Refactor] : 권한 수정 및 Navbar Profile 수정

src/components/workspace/SurveyCard.jsx
add surveycard import
어떤 변경 사항이 있나요?
=> [Refactor] : add surveycard import

package.json, src/components/api/ApiCall.js, src/components/user/Login.jsx, src/components/workspace/SurveyCard.jsx, src/pages/workspace/api.js
=> [Refactor] : CORS 설정

src/pages/workspace/api.js
- 공통 axios 호출 File 추가
- 
어떤 변경 사항이 있나요?
=> [Feat] : 공통 axios 호출 File 추가

src/components/common/Search.jsx, src/components/common/SearchResultTable.jsx, src/components/common/SurveyPostContainer.jsx, src/components/community/ChildCommentForm.jsx, src/components/community/Comment.jsx, src/components/community/CommunityDetail.jsx, src/components/community/CommunityPost.jsx, src/components/community/EditCommunityPost.jsx, src/components/community/ParentsComment.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx
=> [Refactor] refactor axios method

src/components/admin/AdminClaimInfo.jsx, src/components/admin/AdminClaimList.jsx, src/components/admin/AdminCommunityList.jsx, src/components/admin/AdminDashboard.jsx, src/components/admin/AdminHeader.jsx, src/components/admin/AdminSurveyList.jsx, src/components/admin/AdminUserInfo.jsx, src/components/admin/AdminUserList.jsx, src/components/surveyCommunity/SurveyListModal.jsx, src/components/user/AdditionalJoin.jsx, src/components/user/ChangePassword.jsx, src/components/user/EmailValidation.jsx, src/components/user/FindPassword.jsx, src/components/user/Join.jsx, src/components/user/Mypage.jsx, src/components/user/MypageCommunity.jsx, src/components/user/MypageCommunityList.jsx, src/components/user/MypageHeader.jsx, src/components/user/MypagePassword.jsx, src/components/user/MypagePasswordChange.jsx, src/components/user/MypagePlan.jsx, src/components/user/MypagePlanDetail.jsx, src/components/user/MypageSurveyCommunity.jsx, src/components/user/MypageSurveyList.jsx, src/pages/workspace/api.js
[Feat] : planDetail 수정
어떤 변경 사항이 있나요?
=> [Feat] : planDetail 수정

src/components/api/ApiCall.js, src/components/user/AdditionalJoin.jsx, src/components/user/EmailValidation.jsx, src/components/user/Login.jsx, src/components/user/MypageHeader.jsx, src/components/user/MypagePlanDetail.jsx, src/components/user/MypageUserInfo.jsx, src/components/user/UserInfoEditForm.jsx, src/pages/admin/AdminLoginPage.jsx
[Feat] : call 수정
어떤 변경 사항이 있나요?
=> [Feat] : call 수정

src/components/survey/surveyInfo/infoTab/SurveyInfo.jsx, src/components/survey/surveyInfo/resultTab/PersonalResult.jsx, src/components/survey/surveyInfo/resultTab/PostResult.jsx, src/components/survey/surveyInfo/resultTab/ResultView.jsx, src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx, src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx, src/pages/survey/CreateScoreSurveyPage.jsx, src/pages/survey/CreateSurveyPage.jsx, src/pages/survey/EditScoreSurveyPage.jsx, src/pages/survey/EditSurveyPage.jsx, src/pages/survey/SurveyInfoPage.jsx, src/routes/Router.js
call메소드 import변경
어떤 변경 사항이 있나요?
=> [Refactor] : call메소드 import변경

src/components/user/Login.jsx
[Refactor] : 로그인 글자 깨짐 수정
어떤 변경 사항이 있나요?
=> [Refactor] : 로그인 글자 깨짐 수정

src/components/common/SurveyCard.jsx, src/components/survey/surveyInfo/infoTab/SurveyInfo.jsx, src/components/surveyCommunity/CommunitySurveyWrite.jsx, src/pages/survey/CreateScoreSurveyPage.jsx, src/pages/survey/SurveyInfoPage.jsx
=> [Refactor] : 설문 생성 해결

src/components/surveyCommunity/CommunitySurveyWrite.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx
설문 참여 시 postId안넘어오는 이슈 해결
어떤 변경 사항이 있나요?
=> [Fix] : postId값 체크

src/components/user/ChangePassword.jsx, src/components/user/Mypage.jsx, src/components/user/MypagePasswordChange.jsx, src/pages/workspace/api.js, src/style/user/MypageHeader.module.css
[Feat] : refresh 토큰 요청 추가
어떤 변경 사항이 있나요?
=> [Feat] : refresh 토큰 요청 추가

src/components/common/SurveyPostContainer.jsx, src/components/workspace/Navbar.jsx, src/components/workspace/WorkspaceHeader.jsx, src/pages/survey/CreateScoreSurveyPage.jsx, src/pages/survey/EditScoreSurveyPage.jsx, src/style/workspace/Main.module.css
- CSS & workspaceState, header CSS, navbar 수정
어떤 변경 사항이 있나요?
=> [Fix] : 헤더 & 네비 & 점수형 설문지 수정

src/components/community/CommunityWrite.jsx, src/components/community/EditCommunityPost.jsx
생성, 수정 시 alert창 제거 및 투표 기능 정리
어떤 변경 사항이 있나요?
=> [Refactor] : 투표 및 게시글 생성 alert수정

src/pages/workspace/api.js
=> [Chore] : 서버 URI 변경

src/components/survey/surveyInfo/resultTab/PostResult.jsx, src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx, src/components/survey/surveyInfo/resultTab/totalOptions/FileList.jsx, src/pages/survey/EditScoreSurveyPage.jsx
설문 엑셀, 파일 URI변경
어떤 변경 사항이 있나요?
=> [Refactor] : 설문 엑셀, 파일 URI변경

src/components/community/CommunityWrite.jsx, src/components/community/EditCommunityPost.jsx, src/components/user/MypagePlanDetail.jsx
투표 및 워크스페이스 생성명 수정
어떤 변경 사항이 있나요?
=> [Refactor] : 투표 및 워크스페이스 생성명 수정

src/components/community/ChildCommentForm.jsx, src/components/community/Comment.jsx, src/components/community/CommunityDetail.jsx, src/components/community/CommunityPost.jsx, src/components/community/ParentsComment.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx
* 버그 수정 
* 유효성 검사 수행
어떤 변경 사항이 있나요?
=> [Bug] : 버그 수정

src/components/common/SurveyPostContainer.jsx, src/components/community/CommunityPost.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx
=> [Refactor] : 게시글 작성 권한 체크

src/components/community/CommunityPost.jsx
=> [Refactor] : 커뮤니티 뷰 수정

src/components/admin/AdminClaimList.jsx, src/components/admin/AdminCommunityList.jsx, src/components/api/ApiCall.js, src/components/common/Header.jsx, src/components/common/OAuth2RedirectHandler.js, src/components/user/AdditionalJoin.jsx, src/components/user/EmailValidation.jsx, src/components/user/FindPassword.jsx, src/components/user/Join.jsx, src/components/user/Login.jsx, src/components/user/Mypage.jsx, src/components/user/MypageCommunity.jsx, src/components/user/MypageCommunityList.jsx, src/components/user/MypageHeader.jsx, src/components/user/MypagePassword.jsx, src/components/user/MypagePasswordChange.jsx, src/components/user/MypagePlan.jsx, src/components/user/MypagePlanDetail.jsx, src/components/user/MypageSurveyCommunity.jsx, src/components/user/MypageSurveyList.jsx, src/components/user/MypageUserInfo.jsx, src/components/user/UserInfoEditForm.jsx, src/pages/admin/AdminClaimInfoPage.jsx, src/pages/admin/AdminClaimListPage.jsx, src/pages/admin/AdminCommunityListPage.jsx, src/pages/admin/AdminLoginPage.jsx, src/pages/admin/AdminMainPage.jsx, src/pages/admin/AdminSurveyListPage.jsx, src/pages/admin/AdminUserInfoPage.jsx, src/pages/admin/AdminUserListPage.jsx
[Refactor] : import 삭제
어떤 변경 사항이 있나요?
=> [Refactor] : import 삭제

src/components/common/SCommunitySearch.jsx, src/components/common/SCommunitySearchResult.jsx, src/components/community/CommunityWrite.jsx, src/components/community/EditChildComment.jsx, src/components/community/EditComment.jsx, src/components/community/ParentsComment.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx, src/components/surveyCommunity/SurveyListModal.jsx
=> [Refactor] : refactor child comment service

src/components/common/ClaimReasonModal.jsx
=> [Refactor] : refactor claim service

src/components/workspace/AdminItem.jsx, src/components/workspace/Item.jsx, src/components/workspace/ManagementModal.jsx, src/components/workspace/MoreMenu.jsx, src/components/workspace/Navbar.jsx, src/components/workspace/ProfileContainer.jsx, src/components/workspace/ShareModal.jsx, src/components/workspace/SurveyCard.jsx, src/components/workspace/WorkspaceModal.jsx, src/pages/workspace/Main.jsx, src/pages/workspace/WorkspaceContext.js, src/style/survey/EditSurveyPage.module.css, src/style/workspace/AdminItem.module.css, src/style/workspace/Main.module.css, src/style/workspace/MoreMenu.module.css, src/style/workspace/Navbar.module.css, src/style/workspace/SurveyCard.module.css
워크스페이스 오류 수정 [ 노션 참고 ]
어떤 변경 사항이 있나요?
=> [Fix] : 워크스페이스 오류 수정

src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx, src/components/surveyCommunity/EditSurveyCommunity.jsx
=> [Refactor] : 설문 게시글 수정

src/components/surveyCommunity/EditSurveyCommunity.jsx
=> [Fix] : 설문게시글 수정 페이지

src/components/surveyCommunity/EditSurveyCommunity.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx, src/style/survey/EditSurveyPage.module.css
=> [Refactor] : 설문 파일, 레이아웃 수정

src/components/community/ChildCommentForm.jsx, src/components/community/Comment.jsx, src/components/community/CommunityDetail.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx
=> [Refactor] : 버그수정

src/components/survey/surveyInfo/infoTab/SurveyInfo.jsx, src/components/survey/surveyInfo/resultTab/SurvePostSelect.jsx
=> [Refactor] :설문 수정

src/components/community/CommunityDetail.jsx, src/components/surveyCommunity/CommunitySurveyWrite.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx
=> [Fix] : 게시물 삭제 리턴

src/components/surveyCommunity/EditSurveyCommunity.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx
=> [Fix] : 썸네일 사이즈 고정

src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/components/surveyCommunity/SurveyListModal.jsx
localStorage에서 로그인 정보가 제대로 불러와지지 않는 이슈 
어떤 변경 사항이 있나요?
=> [Refactor] : 설문 게시글 상세 로그인 정보 수정

src/components/survey/surveyForm/QuestionComp.jsx, src/components/survey/surveyForm/ScoreQuestion.jsx, src/components/survey/surveyForm/options/ChoiceOption.jsx, src/components/survey/surveyForm/score/ScoreChoiceOption.jsx, src/pages/survey/CreateScoreSurveyPage.jsx, src/pages/survey/CreateSurveyPage.jsx, src/pages/survey/EditScoreSurveyPage.jsx, src/pages/survey/EditSurveyPage.jsx
=> [Feat] : 설문 옵션 중복 제거

src/components/workspace/ShareItem.jsx, src/components/workspace/ShareModal.jsx, src/components/workspace/SharedHistoryItem.jsx, src/pages/survey/SurveyInfoPage.jsx, src/pages/workspace/Main.jsx, src/style/workspace/MoreMenu.module.css, src/style/workspace/ShareItem.module.css, src/style/workspace/ShareModal.module.css, src/style/workspace/SharedHistoryItem.module.css, src/style/workspace/WorkspaceHeader.module.css
=> [Fixs] : 워크스페이스 오류 수정 

src/components/survey/surveyInfo/resultTab/PersonalResult.jsx, src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx, src/components/survey/surveyInfo/resultTab/UserList.jsx
api 변경 nickname -> userId
어떤 변경 사항이 있나요?
=> [Refactor] : 개별 응답 수정

src/components/surveyCommunity/SurveyCommunityDetail.jsx
=> [Refactor] : 비회원 설문 게시글 조회

src/components/workspace/ShareModal.jsx, src/components/workspace/SharedHistoryItem.jsx, src/components/workspace/WorkspaceModal.jsx, src/pages/workspace/Main.jsx, src/pages/workspace/api.js, src/style/workspace/ShareItem.module.css, src/style/workspace/ShareModal.module.css, src/style/workspace/SharedHistoryItem.module.css
- 외부공유 마감날짜 수정기능 추가 
- 공유모달 UI 변경
Resolves : #200 
어떤 변경 사항이 있나요?
=> [Feat] : 외부공유 마감날짜 수정기능 추가 & 공유 모달 UI 변경

src/components/surveyCommunity/survey/FileOption.jsx, src/components/surveyCommunity/survey/SurveyQuestion.jsx
설문 참여 파일 크기 제한 -> 5MB
어떤 변경 사항이 있나요?
=> [Refactor] : 설문 참여 파일 크기 제한

src/components/surveyCommunity/survey/SurveyForm.jsx, src/components/surveyCommunity/survey/SurveyQuestion.jsx, src/components/workspace/SharedFooter.jsx, src/pages/survey/CreateScoreSurveyPage.jsx, src/pages/survey/CreateSurveyPage.jsx, src/pages/survey/EditScoreSurveyPage.jsx, src/pages/survey/EditSurveyPage.jsx, src/pages/survey/SurveyInfoPage.jsx, src/pages/workspace/SharedSurvey.jsx, src/style/workspace/SharedSurvey.module.css
공유 양식 초기화 기능 추가 & 설문 폼 CSS 수정
어떤 변경 사항이 있나요?
=> [Feat] : 공유 양식 초기화 기능 추가 & 설문 폼 CSS 수정 

src/components/common/Plan.jsx, src/components/common/SCommunitySearchResult.jsx, src/components/common/SearchResultTable.jsx, src/components/common/SurveyPostContainer.jsx, src/components/community/CommunityPost.jsx, src/components/community/CommunityWrite.jsx, src/components/community/EditCommunityPost.jsx, src/components/survey/surveyForm/EditSurveyTitle.jsx, src/components/surveyCommunity/CommunitySurveyWrite.jsx, src/components/surveyCommunity/EditSurveyCommunity.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx, src/components/user/Join.jsx, src/components/user/Login.jsx, src/components/user/MypagePlanDetail.jsx, src/style/surveyCommunity/CommunitySurveyWrite.module.css
=> [Feat] : 양식 지우기 기능

src/components/community/CommunityWrite.jsx, src/components/community/EditCommunityPost.jsx, src/components/surveyCommunity/EditSurveyCommunity.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx
=> [Refactor] : refactor image service

src/components/workspace/ManagementModal.jsx, src/components/workspace/ShareItem.jsx, src/components/workspace/WorkspaceModal.jsx, src/pages/workspace/Main.jsx
워크스페이스 키 이벤트 & 오류 수정
Resolves : #209]
어떤 변경 사항이 있나요?
=> [Fix] : 워크스페이스 키 이벤트 & 오류 수정

src/components/admin/AdminClaimInfo.jsx, src/components/admin/AdminClaimList.jsx, src/components/admin/AdminCommunityList.jsx, src/components/admin/AdminDashboard.jsx, src/components/admin/AdminSurveyList.jsx, src/components/admin/AdminUserInfo.jsx, src/components/admin/AdminUserList.jsx, src/components/api/ApiCall.js, src/components/user/Join.jsx, src/components/user/MypageCommunityList.jsx, src/components/user/MypageSurveyList.jsx, src/components/user/UserInfoEditForm.jsx
[Refactor] : console 정리
어떤 변경 사항이 있나요?
=> [Refactor] : console 정리

src/components/community/CommunityDetail.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx
=> [Refactor] : refactor detail page

src/components/survey/surveyForm/options/ChoiceOption.jsx, src/components/survey/surveyForm/score/ScoreChoiceOption.jsx, src/components/survey/surveyInfo/resultTab/PersonalResult.jsx, src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx, src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx, src/pages/survey/CreateScoreSurveyPage.jsx, src/pages/survey/CreateSurveyPage.jsx, src/pages/survey/EditScoreSurveyPage.jsx, src/pages/survey/EditSurveyPage.jsx
=> [Fix] : 설문 정렬 수정

src/components/common/BarChart.jsx, src/components/survey/fields/ChoiceField.jsx, src/components/survey/surveyForm/options/ChoiceOption.jsx, src/components/survey/surveyForm/score/ScoreChoiceOption.jsx, src/components/survey/surveyInfo/resultTab/PersonalResult.jsx, src/components/survey/surveyInfo/resultTab/PostResult.jsx, src/components/survey/surveyInfo/resultTab/ResultView.jsx, src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx, src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx, src/components/survey/surveyInfo/resultTab/SurvePostSelect.jsx, src/components/surveyCommunity/CommunitySurveyWrite.jsx, src/pages/survey/CreateSurveyPage.jsx, src/pages/survey/EditScoreSurveyPage.jsx, src/pages/survey/EditSurveyPage.jsx
=> [Comment] : 설문 콘솔 제거

src/components/common/ClaimReasonModal.jsx, src/components/community/Comment.jsx, src/components/community/CommunityDetail.jsx, src/components/community/CommunityPost.jsx, src/components/community/CommunityTable.jsx, src/components/community/CommunityWrite.jsx, src/components/community/EditCommunityPost.jsx, src/components/community/ParentsComment.jsx
=> [Refactor] : 콘솔 확인

src/components/common/SCommunitySearch.jsx, src/components/common/SCommunitySearchResult.jsx, src/components/common/Search.jsx, src/components/common/SearchResultTable.jsx, src/components/common/SurveyCard.jsx, src/components/common/SurveyPostContainer.jsx, src/components/community/EditComment.jsx, src/components/community/ParentsComment.jsx, src/components/surveyCommunity/EditSurveyCommunity.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx
=> [Refactor] : refactor

package-lock.json, package.json, src/components/common/SurveyPostContainer.jsx, src/components/survey/surveyInfo/resultTab/PersonalResult.jsx, src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx, src/components/workspace/AdminItem.jsx, src/components/workspace/Item.jsx, src/components/workspace/ManagementModal.jsx, src/components/workspace/MoreMenu.jsx, src/components/workspace/Navbar.jsx, src/components/workspace/SSEComponent.jsx, src/components/workspace/ShareModal.jsx, src/components/workspace/SharedHistoryItem.jsx, src/components/workspace/SurveyCard.jsx, src/pages/workspace/Main.jsx, src/pages/workspace/WorkspaceContext.js, src/pages/workspace/authenticationApi.js, src/style/workspace/Main.module.css, src/style/workspace/SharedHistoryItem.module.css
=> [Refacor] : 통합 배포

src/components/api/ApiCall.js, src/components/user/MypageHeader.jsx, src/pages/admin/AdminLoginPage.jsx
[Refactor] : 프로필 오류 수정
어떤 변경 사항이 있나요?
=> [Refactor] : 프로필 오류 수정

src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx, src/pages/survey/SurveyInfoPage.jsx
=> [Fix] : 설문 순서 정렬

src/components/api/ApiCall.js, src/components/user/MypageHeader.jsx, src/pages/admin/AdminLoginPage.jsx
[Refector] : 프로필 오류 수정
어떤 변경 사항이 있나요?
=> [Refector] : 프로필 오류 수정

src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
=> [Fix] : 점수 설문 정렬 수정

src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx, src/pages/survey/SurveyInfoPage.jsx
=> [Comment] : 주석제거

src/components/workspace/Navbar.jsx, src/components/workspace/SSEComponent.jsx, src/pages/workspace/Main.jsx, src/pages/workspace/WorkspaceContext.js
- SSE 제거, console 제거
어떤 변경 사항이 있나요?
=> [Refactor] : SSE 제거, console 제거

src/pages/workspace/Authorization.jsx
- 공유 메일 에러 메시지 수정
어떤 변경 사항이 있나요?
=> [Refactor] : 공유 메일 에러 메세지 수정 

src/components/common/OAuth2RedirectHandler.js, src/pages/workspace/api.js
[Feat] : Refresh token 예외 처리
어떤 변경 사항이 있나요?
=> [Feat] : Refresh token 예외 처리

src/components/user/MypageHeader.jsx
[Feat] : 마이페이지 로그인 접근 제한
어떤 변경 사항이 있나요?
=> [Feat] : 마이페이지 로그인 접근 제한

src/components/common/ClaimReasonModal.jsx, src/components/common/SCommunitySearch.jsx, src/components/common/Search.jsx, src/components/common/SearchResultTable.jsx, src/components/community/ChildCommentForm.jsx, src/components/community/CommunityDetail.jsx, src/components/community/CommunityPost.jsx, src/components/community/CommunityTable.jsx, src/components/community/CommunityWrite.jsx, src/components/community/EditCommunityPost.jsx, src/components/surveyCommunity/CommunitySurveyWrite.jsx, src/components/surveyCommunity/EditSurveyCommunity.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/components/surveyCommunity/SurveyCommunityWrite.jsx, src/pages/workspace/api.js, src/style/BizModal.module.css, src/style/Search.module.css, src/style/community/ChildComment.module.css, src/style/community/ChildCommentForm.module.css, src/style/community/Comment.module.css, src/style/community/CommunityDetail.module.css, src/style/community/CommunityWrite.module.css, src/style/community/ParentsComment.module.css, src/style/community/Table.module.css, src/style/community/VoteWrite.module.css, src/style/surveyCommunity/CommunitySurveyWrite.module.css, src/style/surveyCommunity/SurveyCommunityDetail.module.css, src/style/surveyCommunity/SurveyCommunityWrite.module.css
[Feat] : 반응형 css 추가
어떤 변경 사항이 있나요?
=> [Feat] : 반응형 css 추가

src/components/common/Header.jsx, src/components/community/ChildCommentForm.jsx, src/style/Header.module.css, src/style/Search.module.css, src/style/community/ChildCommentForm.module.css, src/style/community/ParentsComment.module.css
[Design] : header 반응형 적용
어떤 변경 사항이 있나요?
=> [Design] : header 반응형 적용

src/components/community/CommunityDetail.jsx, src/components/community/CommunityTable.jsx, src/components/community/MobildChart.jsx, src/components/community/VoteResult.jsx, src/components/surveyCommunity/CommunitySurveyWrite.jsx, src/components/surveyCommunity/SurveyCommunityDetail.jsx, src/style/Header.module.css, src/style/community/Comment.module.css, src/style/community/ParentsComment.module.css, src/style/community/Table.module.css, src/style/community/VoteResult.module.css
[Design] : vote chart 반응형 적용
어떤 변경 사항이 있나요?
=> [Design] : vote chart 반응형 적용

src/components/surveyCommunity/SurveyCommunityWrite.jsx, src/components/surveyCommunity/SurveyListModal.jsx, src/style/BizModal.module.css, src/style/surveyCommunity/CommunitySurveyWrite.module.css, src/style/surveyCommunity/SurveyCommunityWrite.module.css
[Design] : 설문 커뮤니티 반응형 적용
어떤 변경 사항이 있나요?
=> [Design] : 설문 커뮤니티 반응형 적용

src/App.css, src/components/surveyCommunity/SurveyCommunityWrite.jsx, src/components/surveyCommunity/SurveyListModal.jsx, src/components/user/Mypage.jsx, src/components/user/MypageHeader.jsx, src/style/user/MypageHeader.module.css, src/style/user/MypageSurveyList.module.css, src/style/user/MypageUserInfo.module.css
[Design] : font 추가, surveyModal 반응형
어떤 변경 사항이 있나요?
=> [Design] : font 추가, surveyModal 반응형

src/components/workspace/AdminItem.jsx, src/components/workspace/ManagementModal.jsx, src/components/workspace/MoreMenu.jsx, src/components/workspace/SSEComponent.jsx, src/components/workspace/SurveyCard.jsx, src/components/workspace/WorkspaceHeader.jsx, src/pages/workspace/Main.jsx, src/pages/workspace/WorkspaceContext.js, src/pages/workspace/api.js
- SSE 기반 관리자 및 연락처 실시간 서비스 제공
어떤 변경 사항이 있나요?
=> [Feat] : SSE 기반 관리자 및 연락처 실시간 서비스 제공
